#!/usr/bin/python
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

import os
import sys
import json

try:
    import sync_db
except ImportError:
    # Useful when running from source tree.
    sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir,
                                 "sync-database"))
    import sync_db

import sync_db.error

try:
    import cx_Oracle
except ImportError as error:
    sys.stderr.write("Error: {0}.\n\n"
                     "Check that cx_Oracle is installed, and that either "
                     "LD_LIBRARY_PATH includes $ORACLE_HOME/lib, or "
                     "$ORACLE_HOME/lib has been added to /etc/ld.so.conf.d "
                     "(and ldconfig has been run).\n".format(error))
    sys.exit(1)

import sync_ui_helper.main

sync_ui_helper.main.run()

